FROM node:16.14-alpine

RUN npm install -g npm@8.12.2

WORKDIR /usr/products

COPY package.json ./
COPY prisma ./prisma/

RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 3332

CMD [ "npm", "run", "dev"]